name: CI
on: [push]
jobs:
  run-tests:
    name: Lint and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install packages
        run: npm ci

      - name: Run ESlint
        run: npm run lint

      - name: Run Jest/Unit Tests
        run: npm run ci:test

      - name: Run Cypress/e2e Tests
        uses: cypress-io/github-action@v4
        with:
          build: npm run build
          start: npm start
  